### ISSUE TITLE
Loss statistic

### ISSUE THREAD

**Issue by dudanov** [cnlohr/cnping#15]
Hi!
I have 2 questions:
1. Why ping started with 100% loss?
2. While ping in progress and screen is filled, loss value is jumping about one pixel cost (for example, 0~0.3%)
I understand that this is not a bug, but rather a small unpleasant features of realization.

**Comment by cnlohr** [comment]
That is a good observation.  I wasn't the person who added the ping loss feature, it looks like it just uses whatever's on-screen to do the calculation.  Are you up for tweaking it to be a some other metric?  Perhaps storing an array of tried vs given up?  I don't believe I have a threshold now for giving up.

**Comment by dreua** [comment]
Here is my fix for this issue: https://github.com/dreua/cnping/commit/43f1ae152b13b6734d4c771431422d871ee66c8d

Should I send a pull request?

**Comment by cnlohr** [comment]
Yes, please make a pull request.  I tried thinking through it once and got confused.
