### ISSUE TITLE
cnping gives cryptic error message when not running as root

### ISSUE THREAD

**Issue by rscullin** [cnlohr/cnping#16]
When running `cnping` as a non-root user, I get a cryptic-ish error:
```
$ ./cnping google.com         
GuiYScaleFactor:   dynamic
Error: Failed to set TTL option
```
The issue is caused by not running `cnping` as `root` (or with `sudo`), and it would be helpful to alert the user that it needs to be run with root privs.

**Comment by 4ndrej** [comment]
It seems that setsockopt(...) in ping.c cause the problem since it should be run as root.
https://github.com/cnlohr/cnping/blob/933806fc806b9052110e0342ef8fc6823ee278de/ping.c#L253

**Comment by cnlohr** [comment]
@rscullin Can you check out the current dev branch and see if it runs well on a mac?

**Comment by rscullin** [comment]
(Super delayed; sorry!)

It now seems to works worse than before. All pings fail (to multiple hosts, on multiple networks), and the original issue of "Failed to set TTL option" when run as a non-root user still exists.

![image](https://user-images.githubusercontent.com/176014/28125741-847f4332-66f5-11e7-92d0-67b8038c2bc1.png)

**Comment by cnlohr** [comment]
Ok... Does it work as root though?  And, I am thinking we probably should clean it up more.

**Comment by cnlohr** [comment]
Whoops.  That was a pretty big bug.  Should be fixed now.  Also if something goes wrong during the normal operations, it should provide a friendly message to the display.

**Comment by rscullin** [comment]
Works great now! Gives an error as non-root, and functions as root.
