### ISSUE TITLE
Failed to set TTL option

### ISSUE THREAD

**Issue by hackrid** [cnlohr/cnping#2]
built from current head

[developer@localhost cnping]$ ./cnping google.com
Error: Failed to set TTL option

strace output:
```
socket(PF_INET, SOCK_RAW, IPPROTO_ICMP) = -1 EPERM (Operation not permitted)
setsockopt(4294967295, SOL_IP, IP_TTL, [255], 4) = -1 EBADF (Bad file descriptor)
write(2, "Error: Failed to set TTL option\n", 32Error: Failed to set TTL option

```

**Comment by cnlohr** [comment]
Needs to be run as "sudo" when installing to /usr/local/bin, you can set the sticky bit.

**Comment by hackrid** [comment]
sticky bit?
ok, I was also facing some proxy trouble. with local host names, it works as sudo.

where does it get its proxy settings from?

**Comment by cnlohr** [comment]
Proxy settings?  That seems odd to me.  Does regular ping support proxy settings?  Typically it uses default routes to get to other ports.

**Comment by hackrid** [comment]
hi charles,
again, my fault. it seems our friendly proxy blocks all pings to the outside world.
could you say what you mean by "sticky bits"?

**Comment by cnlohr** [comment]
OH! ok... so, on Linux systems you have to have root privileges to ping out.  So, you can make cnping 'root' but run it as a user and allow it to maintain its root status.

**Comment by hackrid** [comment]
- run cnping as root
- don't put a proxy between you and ping target
