### ISSUE TITLE
graph display glitched when window width > 2048px

### ISSUE THREAD

**Issue by tjb0607** [cnlohr/cnping#20]
When window width is greater than 2048px, it shows the same data twice, once starting at the 1st pixel, and once starting at the 2049th pixel on the X axis:

![image](https://cloud.githubusercontent.com/assets/1190870/24489265/25b4b592-14d1-11e7-96b6-a272797a9789.png)

**Comment by cnlohr** [comment]
This is because of the size of the ring buffer... Perhaps we could increase the constant, though I haven't thought through the implications of such.  Mind changing PINGCYCLEWIDTH  to 4096 and seeing if it breaks anything?

**Comment by cnlohr** [comment]
...or 8192!

**Comment by cnlohr** [comment]
It must be a power of two!

**Comment by cnlohr** [comment]
Fixed in the dev branch.  Give it a shot.
