### ISSUE TITLE
(auto) scaling vertical axis

### ISSUE THREAD

**Issue by hackrid** [cnlohr/cnping#3]
with local ping targets, delays are really small.
might it be useful to add an option to auto scale the vertical axis ?

**Comment by cnlohr** [comment]
Oooh... Do you mind if it's a command-line parameter? 

Also, if you want to modify it to take command line parameters properly, I'm game!  Interested in contributing or just commenting?

**Comment by hackrid** [comment]
I'm also interested in contributing. but I'm not that experienced with gui programming. I will have a look.
any hint is welcome ;)

**Comment by cnlohr** [comment]
this is barely GUI :-p

**Comment by hackrid** [comment]
well then. I really like non-gui tools like this ;)

**Comment by hackrid** [comment]
#4 addresses my needs

**Comment by cnlohr** [comment]
Automatic would be neat, too.  I am still thinking about making this thing accept ping-style command-line arguments, like -s, -i, etc.

**Comment by hackrid** [comment]
regarding auto scaling, what do you think about this:
let the current response tme maximum (https://github.com/cnlohr/cnping/blob/master/cnping.c#L179) act as scaler for other values to use the complete range of screen y ?
