### ISSUE TITLE
Segfault, "No protocol specified"

### ISSUE THREAD

**Issue by ChristianRomberg** [cnlohr/cnping#35]
Hi, I recently upgraded to Ubuntu 17.10 which uses Wayland instead of X11. cnping used to work before the upgrade, and now it doesn't. I freshly installed cnping from source to make sure I got the latest version, but it segfaults after saying "No protocol specified". Screenshot below.
![screenshot from 2018-01-23 20-53-50](https://user-images.githubusercontent.com/25772118/35297575-afb005d6-007f-11e8-9bf1-5d128a1bfed1.png)

If you need anything, my grahpics settings etc, just leave a comment. Thanks!

**Comment by ChristianRomberg** [comment]
Done a little debugging (courtesy of some `printf`) and it turns out [XOpenDisplay(NULL)](https://github.com/cnlohr/cnping/blob/master/CNFGXDriver.c#L166) returns `NULL`. Not sure why, I thought XWayland would take care of it. Other X Windows (such as xeyes) work fine.

**Comment by ChristianRomberg** [comment]
Ok. Got it. It's the setuid causing trouble. If I follow the instructions outlined [here](https://wiki.archlinux.org/index.php/wayland#Running_graphical_applications_as_root), everything works.

**Comment by cnlohr** [comment]
hmm, that is annoying it doesn't "just" work.  But there's really no other way around it

**Comment by ChristianRomberg** [comment]
I guess one way to deal with it would be to build 2 seperate applications, one with elevated permissions (which does the pinging) and one for plotting. Having to execute those commands before using this awesome program is just a pita

**Comment by cnlohr** [comment]
indeed!  Sounds like something that needs to be complained about for the people XWayland ppl to address.

**Comment by dreua** [comment]
Maybe we should try using capabilities instead of setuid before doing anything more complex. See this article for a short overview: https://www.insecure.ws/linux/getcap_setcap.html

**Comment by ChristianRomberg** [comment]
That works brilliantly! Thanks. If there aren't any major drawbacks to this I'm gonna do a PR

**Comment by cnlohr** [comment]
@dreua  thank you so much for that.  I had no idea it existed.

**Comment by dreua** [comment]
I experienced some really strange behavior when upgrading from the old (setuid) to the new (getcap) version: 
1. On `linuxinstall` the file `/usr/local/bin/cnping` is overwritten but the setuid-bit from the file being previously at that location (from the old version) is for some reason (bug or feature in `cp`?) still present in the new version.
2. Now my cnping has both, the setuid bit and the cap_net_raw capability, and I get the same "No protocol specified" error as @ChristianRomberg. If I remove either the setuid bit or the cap_net_raw capability it works fine.

Can someone explain 1 or 2? Does someone experience the same? 

This happens both on Fedora 26 and 27 in X11 mode. (Wayland is available but not activated.)

Proposed workaround: Add `sudo rm /usr/local/bin/cnping`or `sudo chmod -s /usr/local/bin/cnping`to the Makefile.

**Comment by cnlohr** [comment]
My recommendation would be to do the first option of removing cnping.

**Comment by ChristianRomberg** [comment]
We could just install it with the coreutils install which clears all the permissions and file flags. Its really only a cosmetic difference which archieves the same goal of removing the setuid.

**Comment by ChristianRomberg** [comment]
Kinda odd though that removing the file capability fixes the issue for @dreua . Not sure whats up with that. But can you confirm that it works when you give it only the capability and not the setuid-flag?

**Comment by dreua** [comment]
Yes, it works fine with the capability only and with the setuid bit only, but both is a problem. (I have no clue why, I guess it's a bug in Fedora.) I just tried your PR and it works fine for me, thanks 👍
