### ISSUE TITLE
Segmentation fault on Linux

### ISSUE THREAD

**Issue by matrix1000** [cnlohr/cnping#38]
Hi I've use Debian GNU/Linux 8.10 (jessie)
Linux ... 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
gcc version 4.9.2 (Debian 4.9.2-10)
Package: libxinerama-dev -> Version: 2:1.1.3-1+b1
Package: libxext-dev -> Version: 2:1.3.3-1
Package: libx11-dev -> Version: 2:1.6.2-3+deb8u1

I've done the following steps:
make clean
make cnping
(getting some unimportent warnings)
./cnping -h 8.8.8.8
Segmentation fault

[2388738.529645] cnping[6511]: segfault at e8 ip 00000000004029fd sp 00007ffefaf33a80 error 4 in cnping[400000+6000]

Same as root.

Do you have an idea?

Warnings from make cnping:
cc  -g -Os -I/opt/X11/include -Wall   -c -o cnping.o cnping.c
cc  -g -Os -I/opt/X11/include -Wall   -c -o CNFGFunctions.o CNFGFunctions.c
cc  -g -Os -I/opt/X11/include -Wall   -c -o CNFGXDriver.o CNFGXDriver.c
CNFGXDriver.c: In function ‘CNFGHandleInput’:
CNFGXDriver.c:217:6: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
  int r;
      ^
CNFGXDriver.c: In function ‘CNFGUpdateScreenWithBitmap’:
CNFGXDriver.c:267:9: warning: variable ‘ls’ set but not used [-Wunused-but-set-variable]
  int r, ls;
         ^
CNFGXDriver.c:267:6: warning: unused variable ‘r’ [-Wunused-variable]
  int r, ls;
      ^
CNFGXDriver.c:266:25: warning: unused variable ‘lbuffer’ [-Wunused-variable]
  static unsigned char * lbuffer;
                         ^
cc  -g -Os -I/opt/X11/include -Wall   -c -o os_generic.o os_generic.c
cc  -g -Os -I/opt/X11/include -Wall   -c -o ping.o ping.c
ping.c: In function ‘ping’:
ping.c:155:21: warning: unused variable ‘r_addr’ [-Wunused-variable]
  struct sockaddr_in r_addr;
                     ^
ping.c:154:6: warning: unused variable ‘i’ [-Wunused-variable]
  int i, cnt=1;
      ^
ping.c:152:12: warning: unused variable ‘val’ [-Wunused-variable]
  const int val=255;
            ^
cc  -g -Os -I/opt/X11/include -Wall   -c -o httping.o httping.c
gcc  -g -Os -I/opt/X11/include -Wall -o cnping cnping.o CNFGFunctions.o CNFGXDriver.o os_generic.o ping.o httping.o -lX11 -lm -lpthread -g -L/opt/X11/lib/

**Comment by cnlohr** [comment]
(1) Make sure there are no issues with your X.  i.e. run xclock.
(2) Run with gdb, i.e. 

```gdb ./cnping```
```run -h 8.8.8.8```

Charles

**Comment by matrix1000** [comment]
Hi cnlohr, ok, I've found a strange issue with my X. Thanks.

**Comment by cnlohr** [comment]
Just wondering what was?
