### ISSUE TITLE
HTTP thread gets maxed out

### ISSUE THREAD

**Issue by goeiecool9999** [cnlohr/cnping#40]
Running the command: "cnping http://192.168.1.1/" where 192.168.1.1 is my Netgear router causes CNping to max out one of it's threads. It works fine when pinging google on HTTP. It might have something to do with my router rate limiting. This is definitely an edge case but probably worth fixing. The framerate goes to ~3 seconds per frame.

Odd pattern
![image](https://user-images.githubusercontent.com/7033575/37764960-47551f64-2dc3-11e8-8cb3-1889ce7ba737.png)
12.5% is one thread maxed out on a hyperthreaded quad-core.
![image](https://user-images.githubusercontent.com/7033575/37764872-11392844-2dc3-11e8-8e5e-6b87b1f3fb13.png)

**Comment by cnlohr** [comment]
Could you wireshark dump a sample of it and post the dump here?

**Comment by goeiecool9999** [comment]
[routerhttpdump.zip](https://github.com/cnlohr/cnping/files/1838147/routerhttpdump.zip)
There you go. It captures packets in groups of 10 and every time a connection reset occurs a new frame is drawn. Should be pretty straight forward to figure out. The router is probably protecting itself against brute force causing an active wait somewhere in the code.

**Comment by goeiecool9999** [comment]
So I wanted to post the dump first but when I look into it appears the code expects a double CRLF at the end of the router's response but for some reason netgears neglects to send the second CRLF. Turns out the problem lays with Netgear!

**Comment by goeiecool9999** [comment]
"The 4xx class of status code is intended for cases in which the client seems to have erred. Except when responding to a HEAD request, the server SHOULD include an entity containing an explanation of the error situation" Oh... It **IS** Netgear's fault...

**Comment by cnlohr** [comment]
Well, I believe we should still work!  I'll try to look at this tonight.

**Comment by cnlohr** [comment]
BUT!!! If you can fix it and test it that would be much preferred!

**Comment by cnlohr** [comment]
shall we close this issue?
