### ISSUE TITLE
High CPU usage (of process "Xorg") while using cnping

### ISSUE THREAD

**Issue by revirescam** [cnlohr/cnping#44]
When using cnping on linux (debian buster), I get 100%  cpu usage.  Even with slow pings - a period of 2 seconds.  Do other people see this too?  If so, is it hard to fix?

![cnping](https://user-images.githubusercontent.com/12305906/42654967-684e7a42-8612-11e8-967b-236c5087043d.png)

**Comment by dreua** [comment]
On Fedora 27 I do see Xorg's CPU-usage rising but not that extreme:

- top shows around 16 % (I guess this is % of one Core)
- Gnome System Monitor shows around 4 % (I guess this is % of all 4 cores together) 

While it doesn't bother me on my quite old system, it is still more than I would expect for a slow ping, maybe I'll have a look at the code after my exams. 
Fist step would be to figure out where and how cnping's threads wait and if that works as expected. Its quite hard to predict if this is a hard to fix imo, could be something obvious as well as some complicated matter with the GUI.

**Comment by dreua** [comment]
One more thing: Have you tried `make linuxinstall` and `cnping <whatever>` afterwards? It installs and sets the cap_net_raw permission for cnping which might be different from running the whole thing via sudo in terms of CPU usage.

**Comment by revirescam** [comment]
Thanks @dreua 

The cap_net stuff makes no difference.

One more data point:  the 100% cpu usage is seen on a lenovo laptop with 4 cores.  So Xorg uses an entire core.  However, on my hp desktop (2 cores), it only uses 25% of one core. MUCH less cpu is used on the desktop.

Why? - well my suspicion is that I don't have my X well configured on the lenovo laptop (I've always torn my hair out in frustration with video drivers on ThinkPads).  This bad configuration leads to higher CPU load. However, on the HP desktop, which probably had a more standard video card, everything works out of the box better, so we have better video support, so less CPU.

I  fiddled briefly with the call to OGUSleep() at the end of cnping.c, but I got nowhere and gave up.  

I'm going to close this, because I don't think it has much value as an open issue.

**Comment by dreua** [comment]
I agree that this might be mainly an issue with your graphics driver but I still wanted to decrease the system load for higher ping times. Care to test my branch/pull request? It can't do anything at 0.02 s ping interval but for higher intervals it should be better. I still wanted to refresh the windows about 5 times a second. If that is still too much for your system increase the .2 in line 676 of cnping.c to whatever fits your needs.

**Comment by cnlohr** [comment]
Yeah, I'm good with that.  If you have like 20 windows open it does get pretty rough even on properly configured systems.

**Comment by revirescam** [comment]
That worked @dreua, thankyou.

New data on CPU usage (sudo ./cnping -p 2 192.168.1.22):
Desktop, previously 25% now 5%
Laptop, previously 100%, now 23%

Great stuff - thanks again @dreua and @cnlohr 
J.
