### ISSUE TITLE
cnping_mac blurry text

### ISSUE THREAD

**Issue by mischnic** [cnlohr/cnping#50]
The text rendered by cnping_mac isn't quite as sharp as in the X11 version (especially on the blue background).

![bildschirmfoto 2018-07-26 um 11 35 07](https://user-images.githubusercontent.com/4586894/43254675-33a9b7b4-90c8-11e8-828e-3f6e81313b7b.png)
![bildschirmfoto 2018-07-26 um 11 35 15](https://user-images.githubusercontent.com/4586894/43254677-33c5e7ae-90c8-11e8-8db3-89496a5b635c.png)

**Comment by cnlohr** [comment]
I don't know anything about this, maybe @Viknet knows?

**Comment by Viknet** [comment]
For some reason I mixed up window size and content size. Image was squished by height of title bar and interpolated.

I created pull request with fix: #51

**Comment by cnlohr** [comment]
Thanks!  Does that fix it, @mischnic ?

**Comment by mischnic** [comment]
> Thanks! Does that fix it, @mischnic ?

Yes! 👍
