### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by Michael137** [cnlohr/cnping#58]
Used it on Windows and liked the tool, now wanted to port it to my freebsd machine. Changes aren't intrusive (i.e. a few ifdefs to add headers) but if anyone objects I can just leave it as a fork

Changes are in this PR: https://github.com/cnlohr/cnping/pull/56

**Comment by dreua** [comment]
Fwiw I think that Charles will merge these when he gets the time. He seems to be busy these days.

**Comment by Michael137** [comment]
no worries
just a place to keep track

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Michael137** [comment]
bump :)

**Comment by cnlohr** [comment]
This was added in PR #56
